"""Create one target-bound diagnostic descendant from frozen fallback donor pairs."""
import argparse,hashlib,json,shutil,sys
from pathlib import Path
import numpy as np
from PIL import Image
import reference_color_bounded_fallback as bounded
import target_contract

def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def pin(p):p=Path(p).resolve();return {'path':str(p),'sha256':sha(p),'byteCount':p.stat().st_size}
def checked(row):
 p=Path(row['path']).resolve();bounded.require(sha(p)==row['sha256'],'Pinned narrow input changed: '+str(p));return p

def save(p,data):p.write_text(json.dumps(data,indent=2)+'\n',encoding='utf-8')
def associations(parent,proposal,projection,target_hash,target_id,part):
 bounded.require(parent['kind']=='literal-reference-rgb-region-descendant-receipt' and parent['diagnosticOnly'] is True and parent['selected'] is False,'Unselected region parent required')
 bounded.require(proposal['kind']=='read-only-approved-cut-face-uv-contour-proposal' and proposal['selected'] is False,'Frozen unselected contour proposal required')
 bounded.require(parent['targetId']==proposal['targetId']==projection['targetId']==target_id and parent['part']==projection['part']==part,'Cross-target/part inputs rejected')
 bounded.require(parent['targetContractSha256']==projection['targetContractSha256']==target_hash,'Stale target contract rejected')
 bounded.require(parent['source']['sha256']==proposal['source']['sha256']==projection['source']['sha256'] and proposal['sourceArrayPin']['sha256']==projection['sourceCornerArrays']['sha256'],'Stale geometry/source arrays rejected')

def main():
 parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--config',type=Path,required=True);parser.add_argument('--output',type=Path,required=True);args=parser.parse_args();cfg=json.loads(args.config.read_text(encoding='utf-8'))
 bounded.require(set(cfg)=={'schemaVersion','kind','diagnosticOnly','targetContract','part','parentRegion','contourProposal','expectedTargets','expectedScopes','limits'},'Explicit narrow diagnostic controls required')
 bounded.require(cfg['schemaVersion']==1 and cfg['kind']=='frozen-visible-skin-fallback-descendant' and cfg['diagnosticOnly'] is True and cfg['limits']=={'sourceDistanceMm':2,'uvChebyshevTexels':4,'normalDegrees':5,'minimumVisibleIncidence':.15},'Exactly frozen reviewed diagnostic bounds required')
 targetpath=checked(cfg['targetContract']);target=target_contract.load(targetpath);parentpath=checked(cfg['parentRegion']);parent=json.loads(parentpath.read_text());proposalpath=checked(cfg['contourProposal']);proposal=json.loads(proposalpath.read_text());projectionpath=checked(parent['parentProjection']);projection=json.loads(projectionpath.read_text());associations(parent,proposal,projection,sha(targetpath),target['id'],cfg['part'])
 bounded.require(proposal['regionReceipt']['sha256']==sha(parentpath),'Contour is not bound to exact parent region')
 auditpath=checked(proposal['residualClassification']);audit=json.loads(auditpath.read_text());preppath=checked(audit['preparation']);prep=json.loads(preppath.read_text());checked(prep['fitReceipt']);bounded.require(audit['targetId']==target['id'] and audit['regionReceipt']['sha256']==sha(parentpath),'Cross-target/stale residual classification rejected')
 frozen={**proposal['frozenInputs'],**parent['frozenInputs'],str(args.config.resolve()):sha(args.config),str(targetpath):sha(targetpath),str(parentpath):sha(parentpath),str(proposalpath):sha(proposalpath),str(projectionpath):sha(projectionpath),str(auditpath):sha(auditpath),str(preppath):sha(preppath)}
 for path,h in frozen.items():bounded.require(sha(path)==h,'Frozen original changed: '+path)
 inputs={'scope':proposal['boundedVisibleFallbackScope'],'fields':projection['projectionLineage'],'regions':parent['lineage'],'contours':proposal['uvContours'],'faceContours':proposal['faceContours'],'arrays':projection['sourceCornerArrays'],'residualMasks':audit['residualMasks'],'parentRgb':parent['derivedRgb'],'raysReceipt':proposal['eightDirectionExactUvVisibility']}
 for row in inputs.values():frozen[str(checked(row))]=row['sha256']
 scope=np.load(inputs['scope']['path'],allow_pickle=False);fields=np.load(inputs['fields']['path'],allow_pickle=False);regions=np.load(inputs['regions']['path'],allow_pickle=False);contours=np.load(inputs['contours']['path'],allow_pickle=False);faces=np.load(inputs['faceContours']['path'],allow_pickle=False);arrays=np.load(inputs['arrays']['path'],allow_pickle=False);masks=np.load(inputs['residualMasks']['path'],allow_pickle=False)
 bounded.require(cfg['expectedTargets']==proposal['boundedCorrectionCounts']['proposedSkinTargetAndSeedWholeSkinFaceVisibleTwoMmTargets'],'Frozen inventory count differs')
 pairs=bounded.validate_pairs(scope,fields,regions,contours,arrays['positions'],prep['uniformScaleForMillimetres'],cfg['expectedTargets']);y,x,sy,sx=(pairs[k] for k in ('targetY','targetX','donorY','donorX'));bounded.require((faces['proposedRole'][pairs['targetFace']]==1).all(),'Whole face proposed role differs');counts={'inner':int(masks['innerDarkFootprint'][y,x].sum()),'shoulder':int(masks['shoulderDarkFootprint'][y,x].sum())};bounded.require(counts==cfg['expectedScopes'],'Frozen inner/shoulder association differs')
 parent_rgb=np.asarray(Image.open(checked(parent['derivedRgb'])).convert('RGB'));child=bounded.apply_frozen_copy(parent_rgb,pairs);out=args.output.resolve();bounded.require(not out.exists(),'Fresh diagnostic output required');out.mkdir();(out/'helpers').mkdir()
 helpers=[Path(__file__).resolve(),Path(bounded.__file__).resolve(),Path(__file__).with_name('test_reference_color_bounded_fallback.py'),Path(__file__).with_name('test_derive_reference_color_bounded_fallback.py'),Path(__file__).with_name('blender_reference_color_preview.py')]
 for helper in helpers:frozen[str(helper.resolve())]=sha(helper);shutil.copyfile(helper,out/'helpers'/helper.name)
 output=out/'derived-bounded-basecolor.png';Image.fromarray(child).save(output);changed=np.any(child!=parent_rgb,axis=2);scope_mask=np.zeros(child.shape[:2],bool);scope_mask[y,x]=True;Image.fromarray(scope_mask.astype('u1')*255).save(out/'frozen-target-mask.png');Image.fromarray(changed.astype('u1')*255).save(out/'actual-changed-mask.png')
 lineage={**pairs,'targetOldParentRgb':parent_rgb[y,x],'donorParentRgb':parent_rgb[sy,sx],'targetNewRgb':child[y,x],'targetCanonicalProposedPhotoRole':contours['proposedPhotoRole'][y,x],'donorCanonicalProposedPhotoRole':contours['proposedPhotoRole'][sy,sx],'targetInnerScope':masks['innerDarkFootprint'][y,x],'targetShoulderScope':masks['shoulderDarkFootprint'][y,x],'donorParentCameraOwner':regions['cameraOwner'][sy,sx],'donorParentBlendWeights':regions['blendWeights'][sy,sx],'donorParentSourcePhotoRoles':regions['sourceRoles'][sy,sx],'donorParentMode':regions['mode'][sy,sx]};np.savez_compressed(out/'literal-donor-lineage.npz',**lineage)
 preview={'kind':'reference-color-diagnostic-preview','diagnosticOnly':True,'span':parent['sharedOrthoSpan'],'arrays':projection['sourceCornerArrays'],'images':{'parent':parent['derivedRgb'],'bounded':pin(output)},'frozenInputs':frozen};save(out/'preview-input.json',preview)
 for path,h in frozen.items():bounded.require(sha(path)==h,'Frozen original changed during narrow derivation: '+path)
 result={'schemaVersion':1,'kind':'frozen-visible-skin-fallback-descendant-receipt','diagnosticOnly':True,'targetId':target['id'],'targetContract':pin(targetpath),'part':cfg['part'],'coordinateSpace':'generator-source','rigRevision':parent['rigRevision'],'source':parent['source'],'parentRegion':pin(parentpath),'contourProposal':pin(proposalpath),'configuration':pin(args.config),'checkedInputs':inputs,'uniformFittedScaleForMillimetres':prep['uniformScaleForMillimetres'],'derivedRgb':pin(output),'lineage':pin(out/'literal-donor-lineage.npz'),'frozenTargetMask':pin(out/'frozen-target-mask.png'),'actualChangedMask':pin(out/'actual-changed-mask.png'),'previewInput':pin(out/'preview-input.json'),'frozenPairs':len(y),'scopeCounts':counts,'actuallyChangedRgbTexels':int(changed.sum()),'identicalDonorRgbTargets':int((~changed[y,x]).sum()),'allOtherRgbPixelsExact':True,'donorColorsReadOnlyFromUntouchedParent':True,'originalGeometryMapsUvNtWIndicesExact':True,'originalNormalOrmPixelsExact':True,'approvedArtworkExact':True,'parentRegionRoleAtlasAndLineageExact':True,'noWholeAtlasOrUnseenFill':True,'normalMaximumDegrees':5,'uvChebyshevMaximumTexels':4,'objectMaximumDistanceMm':2,'actualDistanceMmP50P95Maximum':np.percentile(pairs['sourceDistanceMm'],[50,95,100]).tolist(),'actualNormalDegreesP50P95Maximum':np.percentile(pairs['normalAngleDegrees'],[50,95,100]).tolist(),'actualUvChebyshevMaximumTexels':int(pairs['uvChebyshevDistance'].max()),'sameFaceTargets':int((pairs['targetFace']==pairs['donorFace']).sum()),'sharedOriginalTwoFaceEdgeTargets':int((pairs['targetFace']!=pairs['donorFace']).sum()),'positiveIncidenceEightViewVisibleOnly':True,'unknownOrMixedFacesTouched':0,'garmentOrProtectedTexelsTouched':0,'roleOwnershipApproved':False,'garmentBoundaryAccepted':False,'selected':False,'staged':False,'nativeCompiled':False,'clientAccepted':False,'frozenInputs':frozen,'limits':['Exactly the frozen555 visible fallback targets are authorized; this is unselected technical RGB copying, not garment ownership approval.','Fourteen known mixed boundary faces remain withheld: they require reviewed boundary intersections/splits, not majority snaps of6-10.6mm triangles.','Other wrong selected-reference cloth and outer-strap/front-side cut discrepancies remain unchanged and unresolved.','Original physical ridge relief and authored normal-map strap traces remain unchanged; RGB copying cannot remove geometric or native shader relief.','Finite eight-direction sourcepoint visibility is not whole-face/internal/animation proof. Native palettes3/8, neighbors, garment edges and actual client acceptance remain pending.']};save(out/'descendant.json',result);print(json.dumps({'receipt':str(out/'descendant.json'),'sha256':sha(out/'descendant.json'),'pairs':len(y),'counts':counts,'changed':int(changed.sum()),'selected':False}),flush=True)
if __name__=='__main__':main()
